name: "Setup javascript env"
runs:
  using: composite
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Set up node
      uses: actions/setup-node@v3
      with:
        cache: pnpm
        node-version: latest

    - name: Install dependencies
      shell: bash
      run: pnpm install
